[package]
name = "handler"
version = "0.1.1"
authors = ["Gnaphron <gnaphron@gmail.com>"]
edition = "2021"

[dependencies]
hyper = "0.14"
gstreamer = { package = "gstreamer", version = "0.17.4", features = ["v1_18"]}
